[package]
name = "slash"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bevy-inspector-egui = "0.24.0"
bevy_asset_loader = "0.21.0"
bevy_gltf_components = "0.5.1"
bevy_registry_export = "0.3.1"
